"""test

Revision ID: 47ccb045ffc8
Revises: 21f9ebb50959
Create Date: 2025-10-25 15:30:19.209354

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "47ccb045ffc8"
down_revision: Union[str, Sequence[str], None] = "21f9ebb50959"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("test", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.create_index(op.f("idx_user_test"), "user", ["test"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_user_test"), table_name="user")
    op.drop_column("user", "test")
    # ### end Alembic commands ###
