"""add column password

Revision ID: 21f9ebb50959
Revises: dbc574252c5b
Create Date: 2025-10-24 17:34:01.363455

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "21f9ebb50959"
down_revision: Union[str, Sequence[str], None] = "dbc574252c5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.create_index(op.f("idx_user_password"), "user", ["password"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_user_password"), table_name="user")
    op.drop_column("user", "password")
    # ### end Alembic commands ###
